name: fmt-th
version: 0.1.0.0
github: "Futarimiti/fmt-th"
license: BSD-3-Clause
author: "Carman Fu"
maintainer: "example@example.com"
copyright: "Carman Fu 2024"
extra-source-files:
  - README.md
  - CHANGELOG.md
# Metadata used when publishing your package
synopsis: Type-safe formatting quasiquoters
category: Text
# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Futarimiti/fmt-th#readme>
dependencies:
  - base >= 4.7 && < 5
  - template-haskell
default-extensions:
  - TemplateHaskell
  - QuasiQuotes
  - LambdaCase
  - TypeSynonymInstances
  - FlexibleInstances
  - InstanceSigs
  - ScopedTypeVariables
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
library:
  source-dirs: src
